### ISSUE TITLE
Create an option in assemble_amplicons.py stage to state min contig length 

### ISSUE THREAD

**Issue by kmgibson** [gwcbi/haphpipe#12]
Create an option in assemble_amplicons.py stage for user to state the minimum contig length in `alignutils.py` in the mummer, show-tiling command. 

Line 331:
cmd3 = ['show-tiling',
        '-a',
        '-i', '%.1f' % 0.6,
        '-l', '%d' % 200,   ------> make an option
        '-v', '%.1f' % 60,
        out_fil,
        '>',
        out_til,
    ]

**Comment by mlbendall** [comment]
You need to add the option to the argparser section and add as a parameter to the function call
